---
services:
  counter:
    build: ./.docker
    platform: linux/amd64
    environment:
      - MAXPLAYERS=32
      - START_MAP=de_dust2
      - START_MONEY=16000
      - BUY_TIME=0.25
      - FRIENDLY_FIRE=1
      - ADMIN_STEAM=0:1:1234566
      - CPU_MHZ=1000
    command: +log on +sv_lan
    ports:
      - 26900:26900/udp
      - 27020:27020/udp
      - 27015:27015/udp
      - 27015:27015
    restart: unless-stopped
